import type {Metadata} from "next";
import {Analytics} from "@vercel/analytics/react";
import {SpeedInsights} from "@vercel/speed-insights/next"
import {Inter} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from '@/components/theme-provider';
import {MainNav} from '@/components/main-nav';

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
        <body className={`${inter.className} h-screen`}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
        >
            <div className="hidden flex-col md:flex">
                <div className="border-b">
                    <MainNav className="mx-6"/>
                </div>
            </div>
            {children}
            <Analytics/>
            <SpeedInsights/>
        </ThemeProvider>
        </body>
        </html>
    );
}
